services:
  nginx:
    image: nginx:latest
    container_name: reverse_proxy
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/extended/:/etc/nginx/conf.d/
    ports:
      - "81:80"
