services:
  # The backend application service
  app:
    image: node:18-alpine
    container_name: backend_app
    working_dir: /app
    volumes:
      - ./:/app
    command: node app.js
    ports:
      - "3000:3000"